### ISSUE TITLE
set up OpenShift with Keylime enabled

### ISSUE THREAD

**Issue by goern** [AICoE/integration-demo-summit-2022#6]
As an Operate First Platform-Ops (a Persona),
I want to deploy a bare metal based cluster,
and I want OpenShift deployed on top of it,
and I want it being registered with ACM,
so that I can have Keylime enabled for all the worker nodes of that cluster.

/kind feature
/priority important-soon

**Comment by codificat** [comment]
Related: https://github.com/AICoE/aicoe-cd/issues/308

**Comment by durandom** [comment]
can't we just re-purpose rick for that? I.e. deploy Keylime to rick?

**Comment by goern** [comment]
we could, but its running a test env for thoth, so a separate cluster for testing keylime would be less disruptive.

**Comment by lukehinds** [comment]
This will be really useful as we were about to start on a keylime operator. When you say 'As an Operate First Operator,' does that mean it will be specific to operate first, or it will be generic kubernetes / openshift operator? (imagine it's the second).

what's rick?

**Comment by goern** [comment]
@lukehinds updated, hopefully, clarified.

**Comment by jimcadden** [comment]
> what's rick?

OpenShift cluster in the [Hetzner environment](https://www.operate-first.cloud/users/support/#hetzner-environment)

**Comment by jimcadden** [comment]
Let's revive this one

**Comment by codificat** [comment]
The registrar and verifier are available. Pinged in https://github.com/operate-first/apps/pull/1955 about the agents, although I believe they are not relevant anymore
