### ISSUE TITLE
create Tekton Task to sign container images

### ISSUE THREAD

**Issue by goern** [AICoE/integration-demo-summit-2022#7]
We want to build a container image to be deployed on the edge, this container image shall be verifiable via a signature generated by an OpenShift pipeline. 

As a Tekton Pipeline,
I want to use a Task,
so that I can sign a container image build in an earlier step,
and so that I can push the container image to quay.io,
and so that I can push the signature to a quay.io

**Acceptance Criteria**
- [x] TektonTask signs image 
- [x] image signature is pushed to quay
- [ ] signature can be verified by some command line tool
- [ ] doc signature management: create/publish/retire/...
- [ ] doc on the roundtrip

**References**
* n/a

/kind feature
/priority important-soon

**Comment by jimcadden** [comment]
cc. @lukehinds

**Comment by lukehinds** [comment]
here is the keyless guide: https://github.com/sigstore/cosign/blob/main/KEYLESS.md

**Comment by goern** [comment]
@lukehinds could one of your team mates take care of creating tekton tasks for that?

**Comment by screeley44** [comment]
@lukehinds - If I understand correctly (and this is only 2nd hand), I think @goern has an existing pipeline where he is producing a container that we want to get signed.

**Comment by goern** [comment]
@harshad16

**Comment by codificat** [comment]
/remove-lifecycle stale

this is not stale, although the part about pushing to quay is not ready because quay.io still does not support it.

**Comment by codificat** [comment]
Status update: all the pieces are now in place.

Images are signed via tekton chains and signatures pushed to quay.io.

Signature verification is ready via cosigned, but it has not yet been enabled on any target cluster.

The other potentially missing item from the acceptance criteria is specific documentation about the setup, although a demo is in the plans

**Comment by cooktheryan** [comment]
@harshad16 this is in place now correct?

**Comment by harshad16** [comment]
@cooktheryan  yes, this a complete task.
We had this in the demo trail runs as well.
