### ISSUE TITLE
acquire hardware for RV car 

### ISSUE THREAD

**Issue by jimcadden** [AICoE/integration-demo-summit-2022#8]
Considering the global supply chain woes and the coming gift holidays we need to get the RV car components ordered very soon. 

Requirements are as follows:
1. Enough computing resources to support RHEL for Edge, MicroShift, Keynote, the app, etc. 
2. Components and sensors with APIs and an active dev community so that we can build some cool AI on top of it. 
3. A car-like aesthetic to remind us all of the inherent life-risking trust we place in technology everyday. 

**References** 
- ~https://f1tenth.org/build.html~
- https://docs.donkeycar.com

**Comment by jimcadden** [comment]
https://f1tenth.org/build.html

**Comment by jimcadden** [comment]
@goern can you add this to the Summit Keynote project board? I seems not the have the authority

**Comment by jimcadden** [comment]
DC hardware arriving ~Nov 25th

**Comment by riekrh** [comment]
I have one complete kit Raspberry Pi kit on hand in case we need a fall-back.

**Comment by MichaelClifford** [comment]
I have received the Waveshare JetRacer Pro kit. but still waiting on the NVIDIA Xavier

**Comment by sub-mod** [comment]
I have received the Waveshare JetRacer Pro kit with RPI 4.
